#!/bin/sh

EULA="1"

. layers/meta-toradex-torizon/scripts/setup-environment $@

# Ensure our custom layer is always active for this build directory.
bitbake-layers add-layer /workdir/torizon/layers/meta-productxy
